[package]
name = "rust_wasm_example"
version = "0.1.0"
authors = ["mokemokechicken"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
  wasm-bindgen = "0.2.67"
  js-sys = "0.3.44"

  [dependencies.web-sys]
  version = "0.3.44"
features = [
  'console',
]
